Models/ErrorViewModel.cs
namespace framedart_project_frontend.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/GlobalModels/ApiResponse.cs
namespace framedart_project_frontend.Models.GlobalModels {
    public class ApiResponse<T> {
        public bool Success { get; set; }
        public string Message { get; set; } = string.Empty;
        public bool PermissionDenied { get; set; }
        public T? Data { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using framedart_project_frontend.Models;

namespace framedart_project_frontend.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger) {
        _logger = logger;
    }

    public IActionResult Index() {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public IActionResult Display ()
    {
        return View("DisplayPrincipal");
    }
}

Controllers/LoginController.cs
using framedart_project_frontend.Service;
using framedart_project_frontend.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace framedart_project_frontend.Controllers {

    public class LoginController : Controller {

        private readonly IAuthService _authService;

        public LoginController (IAuthService authService) {
            _authService = authService;
        }

        public ActionResult VerifyToken() {
            return RedirectToAction("Index");
        }

        public IActionResult Index() {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Login (string usuario, string senha) {

            var authenticated = await _authService.Authenticate(usuario, senha);

            if (!authenticated)
                return Json(new { success = false, message = "Usuário ou senha inválidos" });

            return Json(new { success = true, redirectUrl = Url.Action("Index", "Home") });
        }

    }
}

Controllers/OrdemServicoController.cs
using Microsoft.AspNetCore.Mvc;

namespace framedart_project_frontend.Controllers {

    [Route("OS")]
    public class OrdemServicoController : Controller {

        [Route("Adicionar")]
        public IActionResult AdicionarOS () {
            return View();
        }

    }
}

Views/Home/DisplayPrincipal.cshtml
@{
    Layout = null;
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
</div>

Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Login - Framed Art</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>

    <!-- Para telas grandes (md ou maior) -->
    <div class="container d-none d-md-flex justify-content-center align-items-center vh-100">
        <div class="card p-4" style="width: 350px;">
            <div class="card-body">
                <img src="~/images/logo.jpg" alt="Logo" class="img-fluid">
                <div class="mb-3" style="margin-top: 3rem">
                    <label for="usuarioMD" class="form-label"><strong>Usuário</strong></label>
                    <input type="text" class="form-control" id="usuarioMD" placeholder="Digite o usuário">
                </div>
                <div class="mb-3">
                    <label for="senhaMD" class="form-label"><strong>Senha</strong></label>
                    <input type="password" class="form-control" id="senhaMD" placeholder="Digite a Senha">
                </div>
                <button class="btn btn-primary w-100" onclick="Login(true)">Entrar</button>
                <div class="text-center mt-3">
                    <a href="#" class="text-decoration-none">Esqueceu a senha?</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Para telas pequenas (menor que md) -->
    <div class="container d-md-none" style="margin-top: 5rem">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card p-4">
                    <div class="card-body">
                        <img src="~/images/logo.jpg" alt="Logo" class="img-fluid">
                        <div class="mb-3" style="margin-top: 3rem">
                            <label for="usuarioSM" class="form-label"><strong>Usuário</strong></label>
                            <input type="text" class="form-control w-100" id="usuarioSM" placeholder="Digite o usuário">
                        </div>
                        <div class="mb-3">
                            <label for="senhaSM" class="form-label"><strong>Senha</strong></label>
                            <input type="password" class="form-control w-100" id="senhaSM" placeholder="Digite a Senha">
                        </div>
                        <button class="btn btn-primary w-100" onclick="Login(false)">Entrar</button>
                        <div class="text-center mt-3">
                            <a href="#" class="text-decoration-none">Esqueceu a senha?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/login.js" asp-append-version="true"></script>

    <script type="text/javascript">

        function Login (icTelaGrande) { 
            
            let campoUsuario = icTelaGrande ? '#usuarioMD' : '#usuarioSM';
            let campoSenha = icTelaGrande ? '#senhaMD' : '#senhaSM';

            var usuario = $(campoUsuario).val();
            var senha = $(campoSenha).val();

            $.ajax({
                url: '@Url.Action("Login", "Login")', 
                type: "POST",
                data: { usuario: usuario, senha: senha },
                async: true,
                success: function (response) {
                    if (response.success) {
                        window.location.href = response.redirectUrl;
                    } else {
                        alert(response.message);
                    }
                },
                error: function () {
                    alert("Erro ao tentar fazer login. Tente novamente!");
                }
            });
        }

    </script>
</body>
</html>

Views/OrdemServico/AdicionarOS.cshtml
<style>

    label {
        font-size: 1.5rem
    }

    .subtitulo {
        font-size: 2rem;
        font-weight: 500
    }

</style>

<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="myModalLabel">Novo Quadro</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-5">
                <div class="row mt-4">
                    <div class="form-group col-lg-4 col-sm-12">
                        <label for="vlAltura">Altura</label>
                        <input type="number" class="form-control" id="vlAltura" placeholder="Em centimetros">
                    </div>

                    <div class="form-group col-lg-4 col-sm-12 mt-3 mt-lg-0">
                        <label for="vlLargura">Largura</label>
                        <input type="number" class="form-control" id="vlLargura" placeholder="name@example.com">
                    </div>

                    <div class="form-group col-lg-4 col-sm-12 mt-3 mt-lg-0">
                        <label for="exampleFormControlInput2">Quantidade</label>
                        <input type="number" class="form-control" id="vlQuantidade" placeholder="name@example.com" value="1">
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="form-group col-lg-6 col-sm-12">
                        <label for="cdFundo">Fundo</label><br />
                        <select id="mySelect2" style="width: 100%">
                            <option value="1">Item 1</option>
                            <option value="2">Item 2</option>
                            <option value="3">Item 3</option>
                        </select>

                    </div>

                    <div class="form-group col-lg-6 col-sm-12 mt-3 mt-lg-0">
                        <label for="cdMoldura">Moldura</label>
                        <input type="email" class="form-control" id="cdMoldura" placeholder="name@example.com">
                    </div>

                </div>

                <div class="row mt-4">
                    <div class="form-group col-lg-6 col-sm-12">
                        <label for="cdVidro">Vidro</label>
                        <input type="email" class="form-control" id="cdVidro" placeholder="Em centimetros">
                    </div>

                    <div class="form-group col-lg-6 col-sm-12 mt-3 mt-lg-0">
                        <label for="cdPapel">Papel</label>
                        <input type="email" class="form-control" id="cdPapel" placeholder="name@example.com">
                    </div>
                </div>

                <div class="mb-3 mt-3">
                    <label for="inputImagem" class="form-label">Escolha as imagens</label>
                    <input type="file" class="form-control" id="inputImagem" accept="image/*" multiple>
                    <small class="text-muted">Apenas imagens (JPG, PNG, GIF, etc.).</small>
                </div>

                <div id="previewContainer" class="text-center mt-3" style="display: none;">
                    <p><strong>Prévia das Imagens:</strong></p>
                    <div id="previewImagens" class="d-flex flex-wrap gap-2"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Salvar</button>
            </div>
        </div>
    </div>
</div>


<div class="body-content mb-5">

    <h1 class="text-center text-lg-start">Adicionar Ordem de Servico</h1>

    <div class="row mt-4">
        <div class="form-group col-lg-6 col-sm-12">
            <label for="exampleFormControlInput1">Cliente</label>
            <input type="email" class="form-control" id="email1" placeholder="name@example.com">
            <small>Para adicionar um cliente, clique <a href="">aqui</a></small>
        </div>

        <div class="form-group col-lg-6 col-sm-12 mt-3 mt-lg-0">
            <label for="exampleFormControlInput2">Data de Entrega</label>
            <input type="email" class="form-control" id="email2" placeholder="name@example.com">
        </div>
    </div>


    <div class="mt-4 d-flex flex-row align-items-center">
        <p class="subtitulo m-0 me-3">Quadros</p>
        <button class="btn-secondary" data-bs-toggle="modal" data-bs-target="#myModal"><i class="fa fa-add"></i></button>
    </div>


</div>

<script>

    // Evento para carregar a imagem e exibir o preview
    document.getElementById("inputImagem").addEventListener("change", function (event) {
        var btnSalvar = document.getElementById("btnSalvar");
        var previewContainer = document.getElementById("previewContainer");
        var previewImagens = document.getElementById("previewImagens");

        var files = event.target.files;

        previewImagens.innerHTML = "";

        // Verifica se o número de arquivos está dentro do limite (máximo 5 imagens)
        if (files.length > 0 && files.length <= 5) {
            previewContainer.style.display = "block";

            // Exibe as imagens selecionadas
            for (let i = 0; i < files.length; i++) {
                let file = files[i];

                if (file.type.startsWith("image/")) {
                    let reader = new FileReader();

                    reader.onload = function (e) {
                        let img = document.createElement("img");
                        img.src = e.target.result;
                        img.className = "img-thumbnail";
                        img.style = "width: 100px; height: auto; border-radius: 5px; margin: 5px;";

                        previewImagens.appendChild(img);
                    };

                    reader.readAsDataURL(file);
                }
            }

            // Habilita o botão salvar se a quantidade de imagens for válida
            btnSalvar.disabled = false;
        } else {
            previewContainer.style.display = "none";
            btnSalvar.disabled = true;

            alert("Selecione no máximo 5 imagens.");
        }
    });

    // Inicializando o Select2
    $(document).ready(function () {
        $('#mySelect2').select2({
            placeholder: 'Digite para buscar...',
            minimumInputLength: 1, // número mínimo de caracteres para disparar a busca
            ajax: {
                url: 'URL_DO_SEU_SERVIÇO_DE_BUSCA', // Aqui você coloca a URL que vai retornar os dados
                dataType: 'json',
                delay: 250, // tempo de espera entre as requisições
                data: function (params) {
                    return {
                        q: params.term // a pesquisa será feita pelo valor da pesquisa 'term'
                    };
                },
                processResults: function (data) {
                    return {
                        results: data.items // o formato esperado pela select2
                    };
                },
                cache: true
            }
        });
    });

    // Função para adicionar um quadro (adapte conforme sua lógica)
    function AdicionarQuadro() {
        var quadro = {
            // Adicione as propriedades do quadro que você deseja
        };

        // Aqui você pode fazer algo com o quadro, como adicionar ao DOM ou enviar para um servidor
        console.log(quadro);
    }

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - framedart_project_frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    @* <link rel="stylesheet" href="~/lib/select2/css/select2.css"> *@
    <!-- Adicionando o CSS do Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />

    <!-- Adicionando o JS do Select2 -->

</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/select2/js/select2.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Framed Art</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrdemServico" asp-action="AdicionarOS">Adicionar OS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - framedart_project_frontend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>